Update etl.yaml

diff --git a/.github/workflows/etl.yaml b/.github/workflows/etl.yaml
--- a/.github/workflows/etl.yaml
+++ b/.github/workflows/etl.yaml
@@ -31,8 +31,18 @@ jobs:
 
       - name: Install Quarto
         run: |
-          QUARTO_URL=$(curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest | grep browser_download_url | grep 'quarto-linux-amd64.deb' | cut -d '"' -f 4)
-          curl -L -o quarto-linux-amd64.deb $QUARTO_URL
+          QUARTO_URL=$(curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest \
+                 | grep "browser_download_url.*quarto-linux-amd64.deb" \
+                 | grep -o "https://[^ \"]*")
+          if [[ -z "$QUARTO_URL" ]]; then
+          echo "Failed to find the Quarto download URL"
+          exit 1
+          fi
+          curl -L -o quarto-linux-amd64.deb "$QUARTO_URL"
+          if [ $? -ne 0 ]; then
+          echo "Failed to download Quarto"
+          exit 1
+          fi
           sudo dpkg -i quarto-linux-amd64.deb
 
       - name: Render .qmd file
